settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: false # experimental feature, enable only for <5 monitors or on paid plans

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Some Systems Non-Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: 280180d9ce48f0157494d88c892d91ea
    name: Motor_Emails
    url: 'https://vchiemails.servicebus.windows.net/'

  - id: f6fe225dd3d53a4ee4f2feb8c07cccca
    name: Salesforce_Prod
    url: 'https://na137.salesforce.com/'

  - id: 4bf799c782fcdcfa0220b3577c867cf3
    name: Mediclic_PagPublica
    url: 'https://www.mediclic.cl/'

  - id: d44a37fa436c86e085898df519efd679
    name: Portal_Dev
    url: 'https://portaldev.mediconecta.com/Login'

  - id: 443db5ad1c212cd439bc88297fd550c0
    name: Portal_Mediclic
    url: 'https://consultas.mediclic.cl/Login'

